### ISSUE TITLE
Formatting conventions in manual

### ISSUE THREAD

**Issue by davydych** [siduction/sidu-manual#38]
When I started to work on the English translation of the manual, I noticed a lack of consistency in connection with the formatting of directory names, file names, etc.
So during my work I tried to apply the formatting that seemed to be used most frequently. Of course, I could not apply this perfectly, because many of the conventions were applied from the first file on.
I made notes on these conventions which I want to discuss with you. After the discussion, we could create a wiki page on such conventions.

1. italics
- expressions in a foreign language
- names of programs, commands, scripts (e.g. *burniso*)
- filenames without path (e.g. *.bashrc*)
- names of variables (e.g. *ServerRoot*)

2. italics and highlighted
- filenames with path (e.g. *`/home/user/filename`*)

3. italics with quotation marks
- directory names without path (e.g. "*Downloads*")
- group names (e.g. "*root.root*")
- options (e.g. "*FollowSymLink*")

5. bold
- directories with path (e.g. **/home/user/**)
- file system types (e.g. **ext4**)
- user names (e.g. **root**, **user1**)
- partition names
- command options (e.g. **- -lines=**)

6. bold and highlighted
- complete command outside a source code block (**`cat file.txt`**)

7. highlighted
- keys (e.g. `ALT`+`CTRL`+`F2`)
- man pages (e.g. `man systemd.slice`)

 
Change I would like to propose:
- command options -> highlighted, e.g. `--lines=`
Then the space between the minus signs would not be necessary.

- some paragraphs contain a lot of bold formatting; I consider this unnecessary for e.g. directory names; italics could be used instead

**Comment by fethomm** [comment]
Without looking at the formatting more closely, I do agree with your proposals regarding highlighted command options and that there is no necessity for lots of bold text. That always sets me off anywhere I see it, same as the inflationary use of exclamation marks. :) A wiki page would indeed be nice, as we might have to apply the changes we agree on also to the DE manual. It would also be a guideline for anybody writing a new chapter.

**Comment by ak-li** [comment]
In Bezug auf die Konsistenz der verschiedenen Formatierungen hast du recht. Es liegt auch darin begründet, dass mit der Reaktivierung des Handbuches teils alte Texte übernommen, teils Inhalte vollständig neu erstellt wurden.

Zur Sache:  
+ Die Wiki Seiten DE\_Home und EN\_Home enthalten bereits einen Teil der Format Konventionen.
+ Das Handbuch ist eine Mischung aus Textdatei und technischen Inhalten wie Programmcode, Codezeilen, Dateinamen, Pfaden, Benutzernamen, Optionen, Variablen, Tastenbezeichnungen und vielem mehr.  
  Die vorgeschlagene harte Struktur wird dem Text als solchem nicht gerecht. Es kommt auch auf den Kontext an.  
  Ein Beispiel aus 0716-systemd-timer:  
  In der de-Datei steht die Zeile

  Wir legen die Datei **backup.timer** im Verzeichnis */usr/local/lib/systemd/system/* mit folgendem Inhalt an.

  und in der en-Datei die gleiche Zeile

  We create the file *backup.timer* in the directory **/usr/local/lib/system/system/** with the following content:

  Im Textprogramm bedeutet *kursiv* betont und **fett** stark betont. So wurde die deutsche Zeile formatiert. Das wichtigste Element ist **backup.timer** das etwas weniger wichtige, aber hervorhebungswürdige Element ist */usr/local/lib/systemd/system/*.

+ Inline Code  
  Die Textauszeichnung `hervorgehoben` stellt analog zu Quellcodeblöcken hauptsächlich inline Code dar. Es handelt sich um mögliche Eingaben oder Ausgaben im Terminal. Das kann eine ganze Befehlszeile sein, nur eine Option oder ein Programmmaufruf. Entscheidend sollte der unmittelbare Bezug zum Terminal sein. Das steht auch im Konflikt mit einer harten Formatierungsstruktur.  
  `man systemd.slice` im Bereich Quellen sieht einfach nur schlecht aus.  
  Für Tasten (z.B. `ALT`+`CTRL`+`F2`) sehr empfehlenswert.  
  Diese Textauszeichnung sollte ich wohl etwas sparsamer verwenden. In der englischen Version hast du einiges geändert, was der Optik und Lesbarkeit zu Gute kommt.

+ Anführungszeichen  
  Im Kontext eines Zitates ist der Inhalt für die Formatierung nicht maßgeblich.
  
Ein Versuch von meiner Seite.  
Ich stelle hier demnächst vermutlich unstrittige Formate in einer Liste zusammen.

Betreff Ausrufezeichen:  
Damit haben wir im Handbuch kein Problem. 47 Dateien mit insgesamt 24 einzelnen Ausrufezeichen im Text.

--------------------------------

You are right about the consistency of the different formatting. It is also due to the fact that with the reactivation of the manual, some old texts were taken over, and some content was completely created from scratch.

To the point:  
+ The wiki pages DE\_Home and EN\_Home already contain some of the format conventions.
+ The manual is a mixture of text file and technical content like program code, lines of code, file names, paths, user names, options, variables, key names and much more.  
  The suggested hard structure does not do justice to the text as such. It also depends on the context.  
  An example from 0716-systemd-timer:  
  The de file contains the line

  Wir legen die Datei **backup.timer** im Verzeichnis */usr/local/lib/systemd/system/* mit folgendem Inhalt an.

  and in the en file the same line

  We create the file *backup.timer* in the directory **/usr/local/lib/system/system/** with the following content:

  In the text program *italic* means emphasized and **bold** means strongly emphasized. This is how the German line was formatted. The most important element is **backup.timer** the slightly less important but worth highlighting element is */usr/local/lib/system/system/*.

+ inline code  
  The text markup `highlighted` represents mainly inline code, analogous to source code blocks. It is possible input or output in the terminal. This can be a whole command line, only one option or a program call. The direct reference to the terminal should be decisive. This also conflicts with a hard formatting structure.  
  `man systemd.slice` in the sources section just looks bad.  
  For keys (e.g. `ALT`+`CTRL`+`F2`) very recommendable.  
  I should probably use this text markup a bit more sparingly. In the English version you have changed some things, which is good for the optics and readability.

+ quotation marks  
  In the context of a quote, the content does not matter for formatting.
  
An attempt from my side.  
I'll put together probably undisputed formats in a list here soon.

Subject exclamation mark:  
We have no problem with this in the manual. 47 files with a total of 24 single exclamation marks in the text.

**Comment by davydych** [comment]
Thank you both for your feedback!

@ak-li:

Using `highlighted text` for everything related to the terminal and for keys sounds reasonable to me.

So do quotation marks for citations (for example: code blocks are often followed by explanations of the individual lines or commands -> citations)

Your points on using bold and italics according to the intended emphasis are also convincing.
I assume that the points I listed under *5. bold* can be written in italics instead. When appropriate, **bold** can be used instead in the individual cases.

Looking forward to your list. 

As soon as we will have agreed on the conventions, I can review the English files one more time (and after that, the German ones).

**Comment by ak-li** [comment]
@davydych  
Please compare the file `0206-iso-dl_de.md` with the English one. I have changed the formats there up to line 143.

Nun der Vorschlag:

1. fett und hervorgehoben
    Nur zur Verwendung in technischem Kontext. Es ist Text, der in dieser Form direkt in ein Terminal eingegeben werden kann, oder eine Ausgabe des Terminals darstellt.  
   - Inline Code, analog zu Quellcodeblöcken.
     Zum Beispiel **`nmcli dev wifi show`**
   - Bezeichnung von Tasten  
     Zum Beispiel **`ALT`**+**`CTRL`**+**`F2`** oder **`Enter`**
2. hervorgehoben
   In Anlehnung an 1. bei Verwendung in technischem Kontext.
   - Alle Dateinamen, Programmnamen (sind ja auch Dateien) und Pfade  
     Zum Beispiel `/home/user/filename` `Inkscape`
   - Befehlsoptionen und deren Werte  
     Zum Beispiel `dev wifi show`, vergleiche unter 1. den vollständigen Befehl.
   - Variablen  
     Zum Beispiel `IFS`
3. fett
   - bei Verwendung in technischem Kontext:
     - Benutzernamen, Gruppennamen  
       Zum Beispiel **root** oder **user1** oder **www-data.developer**
     - Dateisystemtypen  
       Zum Beispiel **ext4**
   - bei Verwendung in textlichem Kontext:
     - Starke Betonung von Textstellen. (Bitte sparsam verwenden.)
     - Gelegentlich Ersatz für Überschriften 4. Ordnung (####).
4. kursiv und Anführungszeichen
   - Alle zuvor genannten Elemente, wenn diese im Kontext als Zitat erscheinen.  
     Zum Beispiel folgt auf einen Codeblock mit Befehlen Text mit Erklärungen. Der im Text zitierte Befehl und seine Optionen werden entsprechend formatiert.  
     Bitte Kodierungsreihenfolge beachten: \*"Beispiel"\* ergibt *"Beispiel"*, "\*schlechtes Beispiel\*" ergibt "*schlechtes Beispiel*". (Das "l" läuft in das schließende Anführungszeichen.)
5. kursiv
   - bei Verwendung in textlichem Kontext:
     - Dezente Betonung von Textstellen. (Bitte sparsam verwenden.)
6. kursiv und hervorgehoben
   - Zur Zeit nicht verwendet.

-------------------------
Now the proposal:

1. Bold and highlighted
   For use in a technical context only. It is text that can be entered directly into a terminal in this form, or is an output of the terminal.  
   - Inline code, analogous to source code blocks.
     For example **`nmcli dev wifi show`**.
   - Designation of keys  
     For example **`ALT`**+**`CTRL`**+**`F2`** or **`Enter`**.
2. highlighted
   Following 1. when used in the technical context.
   - All file names, program names (they are also files) and paths  
     For example `/home/user/filename` `Inkscape`
   - Command options and their values  
     For example `dev wifi show`, compare under 1. the complete command.
   - Variables  
     For example `IFS`.
3. Bold
   - when used in a technical context:
     - User names, group names  
       For example **root** or **user1** or **www-data.developer**.
     - File system types  
       For example **ext4**
   - when used in a textual context:
     - Strong emphasis on text passages. (Please use sparingly).
     - Occasionally substitute for 4th order headings (####).
4. Italic and quotation marks
   - All of the previously mentioned elements when they appear in context as a quote.  
     For example, a code block with commands is followed by text with explanations. The command quoted in the text and its options are formatted accordingly.
    Please note coding order: \*"command"\* gives *"command"*, "\*bad command\*" gives "*bad command*". (The "d" runs into the closing quotation mark).
5. italic
   - when used in textual context:
     - Discreet emphasis of text passages. (Please use sparingly).
6. Italic and highlighted
   - Currently not used.

**Comment by ak-li** [comment]
@davydych 

Please also compare the files [0702-sys-admin-gen_en.md](https://github.com/siduction/sidu-manual/blob/WIP/data/en/0702-sys-admin-gen_en.md) and [0702a-sys-admin-gen_en.md](https://github.com/siduction/sidu-manual/blob/WIP/data/en/0702a-sys-admin-gen_en.md)  
In 0207a I changed the section "systemd.service", and I think it's looking better.

Already looking forward to your reply.

**Comment by davydych** [comment]
@ak-li 

I agree, both files are looking way better now.

I was a little concerned that there would be too much `highlighting`, but I've tested some paragraphs with a lot of directory names and it doesn't look bad. Anyway, we can still change this in the future if necessary.

Two things I want to add:
- key combinations without spaces between the keys and the plus signs, i.e. **`ALT`**+**`CTRL`**+**`F2`** instead of **`ALT`** + **`CTRL`** + **`F2`** (just mentioning it because I've seen both variants during my review and decided to use the alternative without spaces)

- program names don't always need to be highlighted
E.g. there is a whole subchapter about systemd. The first time (in 0710-systemd-start) **systemd** is written bold, after that just plain systemd. 

So, if @fethomm and @hhl are okay with these conventions, I can apply them in the English manual.

**Comment by ak-li** [comment]
@davydych 

Auf deine Anregung hin habe ich die Begriffe "-s" und "--kill-who=" in den Zeilen 66 und 67 der Datei 0702a noch einmal getestet, jeweils mit Anführungszeichen und als fetten Text.
Ich halte die Formatierung als hervorgehobener Text trotz der vielen Hervorhebungen immer noch für die beste. Es verdeutlicht die Verwendung im Terminal. Außerdem ist der Text im Vergleich zur vorherigen Version besser lesbar. Zusätzlich fällt auf, dass in der Zeile 68 das Wort "pkill" kursiv gesetzt ist.  
Genau hier und in deinem Beispiel 0710-systemd-start wird der Unterschied zwischen dem Kontext Text und dem Kontext technischen Definition und Erklärung deutlich. Deshalb habe ich in der obigen Liste unter 3. eine Zeile hinzugefügt.

Ich stimme dir zu, dass Tastenkombinationen ohne Leerzeichen besser aussehen. Wir können das mit `grep` und `sed` leicht suchen und ändern.

Wir sind auf dem richtigen Weg.  
Was denkst du über 2. und 5.?

---

At your suggestion, I tested the terms "-s" and "--kill-who=" in lines 66 and 67 of file 0702a, once with quotes and once as bold text.
I still feel the formatting as highlighted text is best at this point, despite a lot of highlighting. It clarifies the usage in the terminal. Also, the text is more readable compared to the previous version. Additionally, it is noticeable that in line 68 the word "pkill" is italicized.  
Exactly here and in your example 0710-systemd-start the difference between the context text and the context technical definition and explanation shows up. Therefore, I have added a line to the above list under 3.

I agree, key combinations without spaces are looking better. We can search and change that with `grep` and `sed` easily.

We are on the right track.  
What do you think about 2. and 5.?

**Comment by davydych** [comment]
@ak-li 

concerning 2. hightlighting and italics:
I cannot think of a situation where a highlighted text would need to be completely in italics.
But we could use italics inside a terminal command that contains variables to be substituted
e.g. <code>systemctl status *unit*</code>
I've seen this formatting in the ArchWiki and I think this makes sense
(cf. table in this chapter: https://wiki.archlinux.org/title/Systemd#Using_units )

The syntax would be: \<code\>systemctl status \*unit\*\</code\>


concerning 5. italics:
Not sure what to add here. Could be used for file system types, but they mainly occur in the context of formatting and here, the type is quite important and probably it's better to write it bold.
Thus, we can use it when emphasis makes sense

**Comment by ak-li** [comment]
@davydych 

concerning 2. hightlighting and italics:  
Your example (<code>systemctl status *unit*</code>) is well-intentioned, but not practical.  
When we started migrating the old manual from almost unreadable HTML code to Markdown, we agreed to stop using HTML code if possible. All that was left was a single format for the footer (see [EN_Home#footer-in-the-new-files](https://github.com/siduction/sidu-manual/wiki/EN_Home#footer-in-the-new-files)).  
Markdown uses the backtic for highlighted parts. We should definitely not change that and reintroduce HTML code in the middle of the document.
We mark variables that are to be substituted with angle brackets `<variables>`.  
Here are two examples:
>Wir erstellen mit einem Texteditor die Datei `home-<user>-www_data.mount` im Verzeichnis `/usr/local/lib/systemd/system/`.  
>"\<user\>" bitte mit dem eigenen Namen ersetzen.

>Ein Programmpaket wird mit diesem Befehl installiert:
>~~~
>apt install <Paketname>
>~~~

I think if you agree, we don't use the formatting highlighted and italic.

concerning 5. italics:
>Not sure what to add here.

Mee too. I think we use this format only in text context.

If you agree too, I will edit the list above.  
We're in the home stretch, aren't we?
  :-))

**Comment by davydych** [comment]
Sure, angle brackets work just as fine. And in that case we don't need hightlighting + italics.

So yes, I agree and it seems like our list is complete :)
Thanks for the constructive discussion!

**Comment by ak-li** [comment]
@davydych @hhl @fethomm @vinzv 

Since we were able to work out a uniform formatting of the manual pages so quickly and constructively, I ask everyone to review wiki pages [DE-Home](https://github.com/siduction/sidu-manual/wiki/DE_Home) and [EN-Home](https://github.com/siduction/sidu-manual/wiki/EN_Home).  
Please note any change requests here.

If there are no suggestions, davydych and I will start working on the files.

**Comment by hhl** [comment]
It looks good to me, but I am not an expert in text formatting.
So, from my side, go!
We will see what the outcome is.
For me, it is important how the pdf- and html-document looks and if it is easy to read and understand,

**Comment by davydych** [comment]
I checked both wiki pages and corrected some minor things:
- added commas where appriopriate
- removed unnecessary periods (Periods are only set after complete sentences.)
- use of capital and small letters

Besides that everything looks fine.

**Comment by ak-li** [comment]
@davydych 

I start by changing the formatting in the "/de" folder.
