### ISSUE TITLE
PDF-Manual with support for people with color vision impairment.

### ISSUE THREAD

**Issue by ak-li** [siduction/sidu-manual#49]
Mister00X brought up the idea of making the manual color coded so that people with color vision deficiencies can easily recognize the code blocks and inline code.
It should be known that all people with color vision deficiency can easily recognize the colors yellow and blue.
Therefore, we changed the background color of the warnings to yellow. The links remain blue as before.

These two variants are up for a vote:
[colortest_green.pdf](https://github.com/siduction/sidu-manual/files/8515403/colortest_green-normal.pdf)
[colortest_orange.pdf](https://github.com/siduction/sidu-manual/files/8515407/colortest_orange-normal.pdf)

@davydych , @fethomm , @hhl , @vinzv , @vinzv 

Please vote on which one is your favorite:

| NAME | orange | green |
| :-------------: | :---: | :----: |
| Mister00X | x |  |
| davydych |  | x |
| der-bud | x |  |
| DonandJoyceWard |  | x |
| hhl |  | x |
| towo2099 |  | x |
| vinzv | x | x |
| ak-li |  | x |

**Comment by ak-li** [comment]
1. Für alle, die sich das Handbuch etwas genauer ansehen möchten. 
   Vollständiges PDF-Handbuch mit farbigem Code hier erhältlich:
   https://github.com/siduction/sidu-manual/tree/WIP/data/de/pdf
2. Die Abstimmung bleibt bis zum 28.4.2022 offen.
3. Der Eintrag in der Abstimmungsliste ist bis dahin änderbar.
----------------------

1. For those who want to have a closer look at the manual. 
   Full PDF manual with colored code available here:
   https://github.com/siduction/sidu-manual/tree/WIP/data/en/pdf
2. Voting will remain open until 4/28/2022.
3. The entry in the voting list can be changed until then.

**Comment by hhl** [comment]
@DonandJoyceWard, please also take a look

**Comment by vinzv** [comment]
Orange might be more eye friendly in the long run. Yet, I'm happy with both colors.

That said, thanks for the initiative @Mister00X! These are things falling off the table way too frequently.

**Comment by hhl** [comment]
For me, it is OK with green, but I also can life with orange.

@ak-li -> One thing/question, would it be possible to use a smaller font in the code-box?
It could be better to read, currently the code breaks too often and jumps out of the code-box <- @Mister00X -> the width of the code and code-box are different! We use for the box itself .95, but not for the code. (page 158, chapter 5.2 IWD as example)

**Comment by Mister00X** [comment]
Looking at page 162 of the green version I can clearly see what you @hhl are talking about.
And I may have already found the cause. In ec396c08d9967660c40e7c6966dd5b708b7f1014 the fontsize for code changed from `\footnotesize` to `\small`.

I am currently experimenting a bit, because a plain `\footnotesize` does not seem to work for me atm.

**Comment by Mister00X** [comment]
I think the problem with code jumping out of the code box can be solved by replacing `\small` with `\footnotesize` here https://github.com/siduction/sidu-manual/blob/37941dc3a71e089982668b5800ba25d581012b7c/development/11-helpfile-pdf-manual-header.tex#L78 and here https://github.com/siduction/sidu-manual/blob/37941dc3a71e089982668b5800ba25d581012b7c/development/11-helpfile-pdf-manual-header.tex#L92-L96 
This results in the pdf looking like this [siduction-manual_green-code_en.pdf](https://github.com/siduction/sidu-manual/files/8542701/siduction-manual_green-code_en.pdf)

Changing `\small` to `\scriptsize` gets rid of most of the line breaks but the code becomes unreadable [siduction-manual_green-code_scriptsize-en.pdf](https://github.com/siduction/sidu-manual/files/8542833/siduction-manual_green-code_scriptsize-en.pdf)

**Comment by hhl** [comment]
Well, it is looking much better!
I could also live with the `\footnotesize`, but for some people it would be too small, I agree with you!

**Comment by Mister00X** [comment]
> Well, it is looking much better!

The code blocks do look better, yes, but inline code begins to look strange with `\scriptsize` too. In the picture below, "cfdisk" is too small, and the bold inline code "mkfs.ext4 /dev/sdaX" too. :-/

![Example screenshot](https://user-images.githubusercontent.com/103577798/164778980-f5600c23-6682-4bd8-b361-d7ca775f5a34.png)

**Comment by hhl** [comment]
> This results in the pdf looking like this [siduction-manual_green-code_en.pdf](https://github.com/siduction/sidu-manual/files/8542701/siduction-manual_green-code_en.pdf)

I prefer this version too, `\scriptsize` is too small

**Comment by Mister00X** [comment]
Shall I send a PR with the `\footnotesize` change now or wait until the vote green vs. orange is decided?

**Comment by hhl** [comment]
Good question, if you send a PR now you maybe have to rebase it. I do not know how @ak-li handle it.

**Comment by ak-li** [comment]
@Mister00X , @hhl ,
I think we're drifting into the wrong turn right now.
Due to previous changes, we have moved away from the professional layout specified by LaTex. 
The more we make individual changes, the further we move away from this professional layout.
We are committing the same mistake that I myself was involved in regarding Issue 48. (Changing text format to prevent page breaks).
@hhl , Please remember your objection to smaller inline code that you raised some time ago.

Some facts:
- We have decided to use color in the manual.
- This implies that the font size and style should not be very different from the text to allow smooth reading.
- We have introduced an additional left margin for code blocks.
- We have limited the width of code blocks to 95%.
- After reviewing the entire PDF, I noticed 20 very poorly readable line breaks in code blocks.
- Several long code blocks with long lines and correspondingly many line breaks in the PDF e.g. MariaDB.
- We have very long lines of code that result in two or more breaks in the PDF. This cannot be changed in principle.
- The output of the `/etc/fstab` file is always hard to read in the PDF. I do not have a solution for this yet.

I have made the following changes:
- In the file `11-helpfile-manual-header.tex` under "code-block style"
  - `linewidth=.98\linewidth,` from before `.95`
  - `xleftmmargin=6pt,` from before `14pt`

Now the code blocks correspond exactly with the text margins. The picture shows the result. After that, only 4 of the 20 bad line breaks are left.
In addition, I will check the long code blocks to see if they can be shortened to a maximum of 60 characters.
With these measures we largely achieve the goals, inline code should be easily recognizable and fluently readable, code blocks with one or few lines should not contain bad line breaks and long code blocks should not contain line breaks inserted by LaTex.


![code-box-fit](https://user-images.githubusercontent.com/66441836/164909876-5e6abc9e-18e8-4280-8968-453150eb6992.png)

**Comment by Mister00X** [comment]
> Due to previous changes, we have moved away from the professional layout specified by LaTex.
> The more we make individual changes, the further we move away from this professional layout.

Agreed.

> In addition, I will check the long code blocks to see if they can be shortened to a maximum of 60 characters.

@ak-li Do you know the actual column limit for listings, is it 60 characters? I couldn't find anything in the manual about this :-/

P.S.: I just remembered something the English version of the manual has *letter* as its paper size while all other (i.e. the German) version has *A4* as paper size. We need to watch out that what we do works for both paper sizes.

**Comment by ak-li** [comment]
@Mister00X 
> P.S.: I just remembered something the English version of the manual has _letter_ as its paper size while all other (i.e. the German) version has _A4_ as paper size. We need to watch out that what we do works for both paper sizes.

In Commit https://github.com/siduction/sidu-manual/commit/283633c64daaeaf2d0a1dbc6058bcb024d6f7709 I changed some in 0717-.. to 65 characters. It follows an addition in 'DE_Home' and 'EN-Home'.

~~~
  A4   = 210*297 mm
Letter = 216*279 mm
~~~

Therefore, what fits in A4 also fits in Letter.

It's nice, the work does not run out.

**Comment by Mister00X** [comment]
> Therefore, what fits in A4 also fits in Letter.

Then we should always look at an A4 version when it comes to code block widths, shouldn't we?

**Comment by DonandJoyceWard** [comment]
Hello everyone.  I just saw this thread this afternoonand have scanned the
two proposed color schemes.  I cannot figure out how to insert my vote on
the matrix ak-li originally sent out, but I think the green text in the
.pdf version is slightly easier to read.  It gets my vote.

I have been going over the English manual draft of GITHUB (slowly, I fear,
because I cannot devote a lot of time to this project right now).  My
initial comments are:
   1.   I think the English manual (I do not read German) has quite a few
instances of "deadwood" that make it hard to read for the
 average siduction user (not necessarily a software engineer or even a
technical person).  By "deadwood", I mean phrases
         that do not add to the intended meaning:  like "in order to" when
"to" alone conveys the same meaning with less verbiage.              There
are several instances of phrases like "tends to" or "make it possible" that
add little or nothing to meaning;  they just                 make the text
harder to read and less concise.
   2.   There are also some awkward sentences where the subject-verb
order obscures the meaning or at least makes the text                 less
readable.
   3.   My early English teachers (a long time ago) stressed to me that
"formal writing" (they meant technical documentation like we           are
providing} should be done in third person - hence, the liberal use of *I,
me, our, my*, and the like were inappropriate for               this kind
of written documentation.  Since I taught at a major university (Texas A&M)
from 1981-2000, I am also keenly                     aware that many
authors nowadays deliberately use first person, active voice writing styles
to be less stilted and academic.             Have  you as a group had a
discussion about such styles and what approach you want this manual to
follow?  There are                 several such points made in a very
concise web post
<https://engineering.usu.edu/students/ewc/writing-resources/technical-writing-standards>
on technical writing that illustrate the above points.

Having opened up this discussion, I think the first two points are
important enough that I should offer a couple of examples of suggested
changes to the numbered sections on GIThub for the full committee's
review.  What is the best way for me to make these suggestions available
for review?  Should I submit new suggested entries directly on the GIThub
or should I just attach them to an email thread to all, as has been done
with the color issue?

Don Ward or Joyce Ward
***@***.***  (Primary)
***@***.*** ***@***.***> (Secondary)
1401 Greenbrier Dr
Sherman, TX 75092
Cells:   Don:    903 818-3381
           Joyce:  903 818-3382

**Comment by davydych** [comment]
@DonandJoyceWard 

Thanks for your feedback and for the link!

1. I will pay more attention to such deadwood. Phrases like "makes it possible" and "tends to" are based on the German version and I tried not to be too creative in my translations ;) But I agree with you.

2. Could you give an example for such an awkward sentence? 

3. The German version is written in a quite casual style and often uses the first person plural pronoun. I agree that the manual would benefit from a more technical / professional style.

Since your suggestions only concern style, you could edit the files in our repository. As a linguist I should be able to figure out what was wrong with my translation. If not, I will ask. 
But first the core team should decide if we should keep the casual style or switch a more professional one.

**Comment by DonandJoyceWard** [comment]
Thanks, davydych.  I will try to edit a couple of files to illustrate the
readability issues I mentioned in points 1 and 2 and notify you and the
team when I have finished them in the repository.  I am certainly not a
linguist, but I have been editing and grading English (mostly US English)
technical writing of graduate and undergraduate students since about 1966.
Nonetheless, there is a lot of subjectivity in the choice of styles.  So, I
wholeheartedly agree that a definitive answer on whether to remain casual
or move (perhaps gradually) to a more formal tone is useful.  Clearly, that
decision belongs to the core team and I have no intent to "dictate by
suggestion".  That would be quite presumptuous for the "new guy".
davydych
Don Ward or Joyce Ward
***@***.***  (Primary)
***@***.*** ***@***.***> (Secondary)
1401 Greenbrier Dr
Sherman, TX 75092
Cells:   Don:    903 818-3381
           Joyce:  903 818-3382

**Comment by fethomm** [comment]
Thanks  for both of your input on the subject of style for a technical manual. For me, personally the casual style, in which the manual is written in (from what I remember, the original was written in EN, then translated to DE) is OK for our project, as long as it does not obfuscate technical clarity. Besides that, it would be far too much work to really change the style to something more professional from a tech writers perspective.

So, my take on this is: wherever phrases seem too flippant, feel free to change them for the sake of clarity, but not attempt to do this for the whole manual. Let's see what others have to say.

**Comment by DonandJoyceWard** [comment]
Thanks, Ferdinand.

Don Ward or Joyce Ward
***@***.***  (Primary)
***@***.*** ***@***.***> (Secondary)
1401 Greenbrier Dr
Sherman, TX 75092
Cells:   Don:    903 818-3381
           Joyce:  903 818-3382

**Comment by ak-li** [comment]
@DonandJoyceWard 
I basically agree with devil's opinion. The tone in the community is quite relaxed and the manual does not claim to be a technical thesis in my opinion.
Since I know how time-consuming the revision of the entire manual is, I do not want to impose this effort on you. Regardless of this, improvements to what you consider to be bad parts of the text are very welcome.

**Comment by DonandJoyceWard** [comment]
Don Ward or Joyce Ward
***@***.***  (Primary)
***@***.*** ***@***.***> (Secondary)
1401 Greenbrier Dr
Sherman, TX 75092
Cells:   Don:    903 818-3381
           Joyce:  903 818-3382

**Comment by ak-li** [comment]
The voting is finished. The result is 3 for orange and 6 for green.
The changes to the green variant will be incorporated immediately.

**Comment by ak-li** [comment]
Closed with commit https://github.com/siduction/sidu-manual/commit/4eadd9518b0e00fb5242b665e4208c41cf9cf7fa
